<a href="https://colab.research.google.com/github/AvishekPritom/Pandas-Learnifng-Tutorial/blob/main/Pandas01_What_kind_of_data_does_pandas_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

#Pandas data table representation

I want to store passenger data of the Titanic. For a number of passengers, I know the name (characters), age (integers) and sex (male/female) data.

In [ ]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)

In [ ]:
df

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss Elizabeth   58  female

#Each column in a DataFrame is a Series

I’m just interested in working with the data in the column Age

In [ ]:
df['Age']

0    22
1    35
2    58
Name: Age, dtype: int64

Note
> When selecting a single column of a pandas DataFrame, the result is a pandas Series. To select the column, use the column label in between square brackets [].

You can create a Series from scratch as well:

In [ ]:
ages = pd.Series([22, 35, 58], name="Age")

About

> A pandas Series has no column labels, as it is just a single column of a DataFrame. A Series does have row labels.

#Do something with a DataFrame or Series

I want to know the maximum Age of the passengers

In [ ]:
df['Age'].max()

58

Note


> As illustrated by the max() method, you can do things with a DataFrame or Series. pandas provides a lot of functionalities, each of them a method you can apply to a DataFrame or Series. As methods are functions, do not forget to use parentheses ().

I’m interested in some basic statistics of the numerical data of my data table

In [ ]:
df.describe()

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

Note


> The describe() method provides a quick overview of the numerical data in a DataFrame. As the Name and Sex columns are textual data, these are by default not taken into account by the describe() method.This is just a starting point. Similar to spreadsheet software, pandas represents data as a table with columns and rows. Apart from the representation, the data manipulations and calculations you would do in spreadsheet software are also supported by pandas. Continue reading the next tutorials to get started!